services:
  client-info:
    build:
      context: ./client-info
    environment:
      NODE_ENV: production
    depends_on:
      - provider
    extra_hosts:
      sso.auth.ru: 172.20.0.1
  client-notes:
    build:
      context: ./client-notes
    environment:
      NODE_ENV: production
    depends_on:
      - provider
    extra_hosts:
      sso.auth.ru: 172.20.0.1
  provider:
    build:
      context: ./provider
    environment:
      NODE_ENV: production
  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
    depends_on:
      - client-info
      - client-notes
      - provider